version: "3"
services:
  todoback:
    image: "todobackend:latest"
    restart: always
    ports:
      - 3001:3001
  todofront:
    image: "todofrontend:latest"
    restart: always
    environment:
      - REACT_APP_API_HOST=todobackend
    ports:
      - 3000:3000
    depends_on:
      - "todoback"
  todotests:
    image: "todotests:latest"
    restart: always
    environment:
      - FRONT_HOST=todofrontend
    depends_on:
      - "todofront"
      - "todoback"
